# Generated by Django 5.1.2 on 2024-11-05 15:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kanban_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='position',
            field=models.IntegerField(default=1),
        ),
    ]
