# Generated by Django 5.1.2 on 2024-11-05 15:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kanban_app', '0002_alter_task_position'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='initials',
            field=models.CharField(blank=True, editable=False, max_length=2),
        ),
    ]
