# Generated by Django 5.1.2 on 2024-12-12 15:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kanban_app', '0008_alter_task_position_alter_user_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='phone_number',
            field=models.CharField(help_text="Telephone number in the format: '999999999'. Up to 15 digits allowed.", max_length=15, null=True),
        ),
    ]
