# Generated by Django 5.1.4 on 2024-12-31 15:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kanban_app', '0009_alter_user_phone_number'),
        ('user_auth_app', '0009_userprofile_email'),
    ]

    operations = [
        migrations.DeleteModel(
            name='User',
        ),
        migrations.AlterField(
            model_name='task',
            name='users',
            field=models.ManyToManyField(related_name='tasks', to='user_auth_app.userprofile'),
        ),
    ]
