# Generated by Django 5.1.4 on 2024-12-14 14:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_auth_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=30)),
                ('last_name', models.CharField(max_length=30)),
                ('email', models.EmailField(blank=True, max_length=254, null=True, unique=True)),
                ('phone_number', models.CharField(help_text="Telephone number in the format: '999999999'. Up to 15 digits allowed.", max_length=15, null=True)),
                ('user_color', models.CharField(max_length=7)),
                ('type', models.CharField(choices=[('user_from_signup', 'User from signup'), ('user_from_contacts', 'User from contacts')], max_length=20)),
                ('initials', models.CharField(blank=True, editable=False, max_length=2)),
            ],
        ),
        migrations.DeleteModel(
            name='UserProfile',
        ),
    ]
