# Generated by Django 5.1.4 on 2024-12-14 14:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user_auth_app', '0002_user_delete_userprofile'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='User',
            new_name='UserProfile',
        ),
    ]
