# Generated by Django 5.1.4 on 2024-12-19 15:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user_auth_app', '0007_alter_userprofile_phone_number'),
        ('user_auth_app', '0007_remove_userprofile_email_and_more'),
    ]

    operations = [
    ]
